import {
  playKick,
  playSnare,
  playHiHat,
  playClap,
  playTom,
  playRim,
  playRide,
  playCymbal,
  playBassNote,
  playChordPad,
  playBass,
  playHorn,
  playSynthStab,
} from "./audioEngine";

export interface Track {
  id: string;
  name: string;
  genre: string;
  bpm: number;
  color: string; // gradient
  artAccent: string; // secondary color for art
  pattern: Array<() => void>[];
  locked?: boolean; // unlockable tracks
  unlockAt?: number; // XP threshold
}

// ─── Genre Presets ───────────────────────────────────────────────────────────

const TRACKS: Track[] = [
  {
    id: "default",
    name: "Blank Canvas",
    genre: "Freestyle",
    bpm: 120,
    color: "linear-gradient(135deg, #1a1a2e, #2a2a4a)",
    artAccent: "#4a4a6a",
    pattern: [
      [playKick],
      [],
      [() => playHiHat(false)],
      [],
      [playSnare, () => playHiHat(false)],
      [],
      [() => playHiHat(false)],
      [playKick],
      [playKick],
      [],
      [() => playHiHat(false)],
      [],
      [playSnare, () => playHiHat(true)],
      [],
      [() => playHiHat(false)],
      [],
    ],
  },
  {
    id: "dusty-crates",
    name: "Dusty Crates",
    genre: "Lo-fi Hip Hop",
    bpm: 82,
    color: "linear-gradient(135deg, #4a3728, #2a1f18)",
    artAccent: "#8b6b4a",
    pattern: [
      [playKick, () => playChordPad([0, 3, 7], 0.8)],
      [],
      [() => playHiHat(false)],
      [],
      [playSnare],
      [],
      [() => playHiHat(false), () => playBassNote(0)],
      [],
      [playKick],
      [() => playHiHat(false)],
      [],
      [() => playBassNote(3)],
      [playSnare, () => playHiHat(false)],
      [],
      [() => playHiHat(false)],
      [playRim],
    ],
  },
  {
    id: "blue-note",
    name: "Blue Note",
    genre: "Jazz",
    bpm: 105,
    color: "linear-gradient(135deg, #1a3a5c, #0a1a2e)",
    artAccent: "#3a7abd",
    pattern: [
      [playKick, () => playRide(true)],
      [],
      [() => playRide(false), () => playBassNote(0)],
      [],
      [() => playRide(true), playRim],
      [],
      [() => playRide(false), () => playBassNote(5)],
      [() => playChordPad([0, 4, 7, 11], 0.5)],
      [playKick, () => playRide(true)],
      [],
      [() => playRide(false), () => playBassNote(7)],
      [],
      [() => playRide(true), playSnare],
      [],
      [() => playRide(false), () => playBassNote(3)],
      [() => playChordPad([-1, 3, 6, 10], 0.5)],
    ],
  },
  {
    id: "golden-era",
    name: "Golden Era",
    genre: "Boom Bap",
    bpm: 92,
    color: "linear-gradient(135deg, #5c3a1a, #2e1a0a)",
    artAccent: "#d4a04a",
    pattern: [
      [playKick, () => playBassNote(0)],
      [],
      [() => playHiHat(false)],
      [() => playHiHat(false)],
      [playSnare],
      [],
      [() => playHiHat(false)],
      [playKick, () => playBassNote(5)],
      [],
      [() => playHiHat(false)],
      [playKick],
      [() => playHiHat(false), () => playTom("high")],
      [playSnare, playClap],
      [() => playTom("mid")],
      [() => playHiHat(true), () => playTom("low")],
      [],
    ],
  },
  {
    id: "concrete-echo",
    name: "Concrete Echo",
    genre: "House",
    bpm: 124,
    color: "linear-gradient(135deg, #2a1a3e, #1a0a2e)",
    artAccent: "#8a4ad4",
    pattern: [
      [playKick, () => playBassNote(0)],
      [],
      [() => playHiHat(false)],
      [],
      [playKick, playClap, () => playHiHat(false)],
      [],
      [() => playHiHat(true)],
      [() => playBassNote(0)],
      [playKick],
      [],
      [() => playHiHat(false)],
      [() => playChordPad([0, 3, 7], 0.4)],
      [playKick, playClap, () => playHiHat(false)],
      [],
      [() => playHiHat(true)],
      [() => playBassNote(5)],
    ],
  },
  {
    id: "slow-drift",
    name: "Slow Drift",
    genre: "Ambient",
    bpm: 72,
    color: "linear-gradient(135deg, #1a2e2a, #0a1a18)",
    artAccent: "#4abda0",
    pattern: [
      [playKick, () => playChordPad([0, 7, 12, 16], 1.2)],
      [],
      [],
      [],
      [playRim],
      [],
      [],
      [() => playBassNote(0)],
      [],
      [],
      [],
      [],
      [playRim, () => playChordPad([5, 12, 17], 1.0)],
      [],
      [],
      [() => playBassNote(7)],
    ],
  },
  {
    id: "velvet-strut",
    name: "Velvet Strut",
    genre: "Funk",
    bpm: 110,
    color: "linear-gradient(135deg, #3e1a3e, #2e0a1a)",
    artAccent: "#d44a8a",
    pattern: [
      [playKick, () => playBassNote(0)],
      [],
      [() => playHiHat(false)],
      [() => playBassNote(0)],
      [playSnare, () => playHiHat(false)],
      [],
      [() => playHiHat(false), () => playBassNote(5)],
      [playKick],
      [],
      [() => playHiHat(false), () => playBassNote(7)],
      [playKick],
      [() => playHiHat(false)],
      [playSnare, playClap],
      [() => playBassNote(3)],
      [() => playHiHat(true)],
      [],
    ],
  },
  {
    id: "midnight-express",
    name: "Midnight Express",
    genre: "Trip Hop",
    bpm: 85,
    color: "linear-gradient(135deg, #1a1a3e, #0a0a1e)",
    artAccent: "#4a4ad4",
    pattern: [
      [playKick, () => playChordPad([-2, 3, 7], 0.9)],
      [],
      [],
      [() => playHiHat(false)],
      [playSnare],
      [],
      [() => playBassNote(0)],
      [],
      [playKick],
      [],
      [() => playHiHat(false)],
      [],
      [playSnare, () => playBassNote(3)],
      [],
      [],
      [playRim, () => playChordPad([0, 5, 10], 0.7)],
    ],
  },
  // ─── Unlockable Tracks ───────────────────────────────────────────────────
  {
    id: "broken-clock",
    name: "Broken Clock",
    genre: "Breakbeat",
    bpm: 140,
    color: "linear-gradient(135deg, #3e2a1a, #1a0a0a)",
    artAccent: "#d47a4a",
    locked: true,
    unlockAt: 500,
    pattern: [
      [playKick, () => playRide(true)],
      [() => playTom("high")],
      [() => playHiHat(false)],
      [() => playTom("mid")],
      [playSnare, playClap, () => playRide(false)],
      [() => playTom("low")],
      [() => playHiHat(false), playRim],
      [playKick],
      [() => playTom("high"), () => playRide(true)],
      [() => playHiHat(true)],
      [playKick, () => playTom("mid")],
      [() => playHiHat(false)],
      [playSnare, () => playTom("low")],
      [playCymbal],
      [() => playHiHat(false), playRim],
      [() => playTom("high")],
    ],
  },
  {
    id: "neon-skyline",
    name: "Neon Skyline",
    genre: "Synthwave",
    bpm: 115,
    color: "linear-gradient(135deg, #2a1a3e, #1a0a2e)",
    artAccent: "#9a4ad4",
    locked: true,
    unlockAt: 1000,
    pattern: [
      [playKick, () => playSynthStab(0), () => playBassNote(0)],
      [],
      [() => playHiHat(false), () => playRide(false)],
      [],
      [playSnare, () => playHiHat(false)],
      [],
      [() => playHiHat(false), () => playSynthStab(4)],
      [playKick, () => playBassNote(5)],
      [],
      [() => playHiHat(false), playRim],
      [playKick, () => playBassNote(7)],
      [() => playHiHat(true), () => playTom("high")],
      [playSnare, playClap],
      [() => playTom("mid")],
      [() => playHiHat(false), () => playTom("low"), () => playSynthStab(7)],
      [() => playBassNote(3)],
    ],
  },
  {
    id: "amen-break-room",
    name: "Amen Break Room",
    genre: "Jungle",
    bpm: 165,
    color: "linear-gradient(135deg, #1a2e1a, #0a1a0a)",
    artAccent: "#4abd6a",
    locked: true,
    unlockAt: 1500,
    pattern: [
      [playKick, () => playRide(true), () => playBassNote(0)],
      [],
      [() => playHiHat(false)],
      [playKick],
      [playSnare, () => playRide(false)],
      [() => playTom("high")],
      [() => playHiHat(false), playRim],
      [],
      [playKick, () => playRide(true)],
      [() => playTom("mid")],
      [() => playHiHat(true)],
      [playKick, () => playBassNote(5)],
      [playSnare, playClap, () => playTom("low")],
      [],
      [() => playHiHat(false), playCymbal],
      [() => playBassNote(7)],
    ],
  },
  {
    id: "kingston-fog",
    name: "Kingston Fog",
    genre: "Dub",
    bpm: 75,
    color: "linear-gradient(135deg, #1a3e1a, #0a2e0a)",
    artAccent: "#4ad44a",
    locked: true,
    unlockAt: 2000,
    pattern: [
      [playKick, () => playBassNote(0)],
      [],
      [],
      [playRim],
      [playSnare],
      [],
      [],
      [() => playBassNote(0)],
      [playKick],
      [],
      [() => playTom("low")],
      [playRim],
      [playSnare, () => playChordPad([0, 3, 7], 0.6)],
      [],
      [],
      [() => playBassNote(5)],
    ],
  },
  {
    id: "cafe-ipanema",
    name: "Café Ipanema",
    genre: "Bossa Nova",
    bpm: 95,
    color: "linear-gradient(135deg, #3e3a1a, #2e2a0a)",
    artAccent: "#d4c44a",
    locked: true,
    unlockAt: 2500,
    pattern: [
      [playKick, () => playBassNote(0)],
      [() => playHiHat(false)],
      [() => playHiHat(false), playRim],
      [() => playHiHat(false)],
      [() => playHiHat(false), () => playTom("high")],
      [() => playHiHat(false)],
      [() => playHiHat(false), playRim, () => playBassNote(5)],
      [() => playHiHat(false)],
      [playKick, () => playChordPad([0, 4, 7], 0.5)],
      [() => playHiHat(false)],
      [() => playHiHat(false), playRim],
      [() => playHiHat(false), () => playTom("mid")],
      [() => playHiHat(false)],
      [() => playHiHat(false)],
      [() => playHiHat(false), playRim, () => playBassNote(7)],
      [() => playHiHat(false), () => playChordPad([-1, 3, 6], 0.5)],
    ],
  },
];

export default TRACKS;
